---
- name: Set distribution family specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure variables are set correctly.
  include_tasks: variable-check.yml

- name: Install cron.
  package:
    name: "{{ cron_package }}"
    state: present

- name: Ensure cron service is started and enabled at boot.
  service:
    name: "{{ cron_service }}"
    state: started
    enabled: true

- name: Schedule cron jobs.
  cron:
    name: "{{ item.name | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    backup: "{{ cron_backup_original_crontab | default(omit) }}"
  with_items: "{{ cron_jobs }}"
  notify: restart cron
  when: cron_jobs is defined
