---
- name: Converge
  hosts: all

  vars:
    cron_jobs:
      - name: Test job.
        minute: "0"
        hour: "5,2"
        job: "ls -alh > /dev/null"
      - name: Test job 2.
        special_time: daily
        job: "ls -alh > /dev/null"

  tasks:
    - name: "Include cron"
      include_role:
        name: "ansible-role-cron"
